<a href="https://colab.research.google.com/github/AssetBayan/Data-Standardisation/blob/main/%EB%8D%B0%EC%9D%B4%ED%84%B0%ED%91%9C%EC%A4%80%ED%99%94_(3%EA%B0%80%EC%A7%80_%ED%91%9C%EB%B3%B8%EC%B6%94%EC%B6%9C_%EB%B0%A9%EB%B2%95).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import seaborn as sns
import pandas as pd
import numpy as np

In [2]:
tips = sns.load_dataset("tips")

# просмотр первых строк
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [3]:
sample_random = tips.sample(n=20, random_state=42)

sample_random

     total_bill   tip     sex smoker   day    time  size
24        19.82  3.18    Male     No   Sat  Dinner     2
6          8.77  2.00    Male     No   Sun  Dinner     2
153       24.55  2.00    Male     No   Sun  Dinner     4
211       25.89  5.16    Male    Yes   Sat  Dinner     4
198       13.00  2.00  Female    Yes  Thur   Lunch     2
176       17.89  2.00    Male    Yes   Sun  Dinner     2
192       28.44  2.56    Male    Yes  Thur   Lunch     2
124       12.48  2.52  Female     No  Thur   Lunch     2
9         14.78  3.23    Male     No   Sun  Dinner     2
101       15.38  3.00  Female    Yes   Fri  Dinner     2
45        18.29  3.00    Male     No   Sun  Dinner     2
233       10.77  1.47    Male     No   Sat  Dinner     2
117       10.65  1.50  Female     No  Thur   Lunch     2
177       14.48  2.00    Male    Yes   Sun  Dinner     2
82        10.07  1.83  Female     No  Thur   Lunch     1
146       18.64  1.36  Female     No  Thur   Lunch     3
200       18.71  4.00    Male    Yes  Thur   Lunch     3
15        21.58  3.92    Male     No   Sun  Dinner     2
66        16.45  2.47  Female     No   Sat  Dinner     2
142       41.19  5.00    Male     No  Thur   Lunch     5

In [5]:
step = 10
sample_systematic = tips.iloc[::step]

sample_systematic

     total_bill    tip     sex smoker   day    time  size
0         16.99   1.01  Female     No   Sun  Dinner     2
10        10.27   1.71    Male     No   Sun  Dinner     2
20        17.92   4.08    Male     No   Sat  Dinner     2
30         9.55   1.45    Male     No   Sat  Dinner     2
40        16.04   2.24    Male     No   Sat  Dinner     3
50        12.54   2.50    Male     No   Sun  Dinner     2
60        20.29   3.21    Male    Yes   Sat  Dinner     2
70        12.02   1.97    Male     No   Sat  Dinner     2
80        19.44   3.00    Male    Yes  Thur   Lunch     2
90        28.97   3.00    Male    Yes   Fri  Dinner     2
100       11.35   2.50  Female    Yes   Fri  Dinner     2
110       14.00   3.00    Male     No   Sat  Dinner     2
120       11.69   2.31    Male     No  Thur   Lunch     2
130       19.08   1.50    Male     No  Thur   Lunch     2
140       17.47   3.50  Female     No  Thur   Lunch     2
150       14.07   2.50    Male     No   Sun  Dinner     2
160       21.50   3.50    Male     No   Sun  Dinner     4
170       50.81  10.00    Male    Yes   Sat  Dinner     3
180       34.65   3.68    Male    Yes   Sun  Dinner     4
190       15.69   1.50    Male    Yes   Sun  Dinner     2
200       18.71   4.00    Male    Yes  Thur   Lunch     3
210       30.06   2.00    Male    Yes   Sat  Dinner     3
220       12.16   2.20    Male    Yes   Fri   Lunch     2
230       24.01   2.00    Male    Yes   Sat  Dinner     4
240       27.18   2.00  Female    Yes   Sat  Dinner     2

In [6]:
sample_stratified = tips.groupby("sex").sample(n=10, random_state=42)

sample_stratified

/tmp/ipykernel_274/985860704.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sample_stratified = tips.groupby("sex").sample(n=10, random_state=42)

     total_bill   tip     sex smoker   day    time  size
194       16.58  4.00    Male    Yes  Thur   Lunch     2
60        20.29  3.21    Male    Yes   Sat  Dinner     2
207       38.73  3.00    Male    Yes   Sat  Dinner     4
216       28.15  3.00    Male    Yes   Sat  Dinner     5
175       32.90  3.11    Male    Yes   Sun  Dinner     2
41        17.46  2.54    Male     No   Sun  Dinner     2
152       17.26  2.74    Male     No   Sun  Dinner     3
154       19.77  2.00    Male     No   Sun  Dinner     4
151       13.13  2.00    Male     No   Sun  Dinner     2
217       11.59  1.50    Male    Yes   Sat  Dinner     2
124       12.48  2.52  Female     No  Thur   Lunch     2
22        15.77  2.23  Female     No   Sat  Dinner     2
226       10.09  2.00  Female    Yes   Fri   Lunch     2
104       20.92  4.08  Female     No   Sat  Dinner     2
32        15.06  3.00  Female     No   Sat  Dinner     2
21        20.29  2.75  Female     No   Sat  Dinner     2
71        17.07  3.00  Female     No   Sat  Dinner     3
93        16.32  4.30  Female    Yes   Fri  Dinner     2
52        34.81  5.20  Female     No   Sun  Dinner     4
57        26.41  1.50  Female     No   Sat  Dinner     2